spring.application.name=springboottutorial

spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:file:/Users/macbook/Desktop/Programming/Spring Boot
spring.datasource.username=manish
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update